// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNewSubscribersSince = `-- name: CountNewSubscribersSince :one
SELECT count(*) FROM subscriptions WHERE channel_id = $1 AND created_at >= $2
`

type CountNewSubscribersSinceParams struct {
	ChannelID pgtype.UUID        `db:"channel_id" json:"channel_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CountNewSubscribersSince(ctx context.Context, arg CountNewSubscribersSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewSubscribersSince, arg.ChannelID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChannelAnalyticsSummary = `-- name: GetChannelAnalyticsSummary :one
SELECT
    COALESCE(SUM(views_count), 0)::bigint AS total_views,
    COALESCE(SUM(likes_count), 0)::bigint AS total_likes,
    COALESCE(SUM(dislikes_count), 0)::bigint AS total_dislikes,
    COUNT(*)::bigint AS total_videos
FROM videos
WHERE channel_id = $1
`

type GetChannelAnalyticsSummaryRow struct {
	TotalViews    int64 `db:"total_views" json:"total_views"`
	TotalLikes    int64 `db:"total_likes" json:"total_likes"`
	TotalDislikes int64 `db:"total_dislikes" json:"total_dislikes"`
	TotalVideos   int64 `db:"total_videos" json:"total_videos"`
}

func (q *Queries) GetChannelAnalyticsSummary(ctx context.Context, channelID pgtype.UUID) (GetChannelAnalyticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getChannelAnalyticsSummary, channelID)
	var i GetChannelAnalyticsSummaryRow
	err := row.Scan(
		&i.TotalViews,
		&i.TotalLikes,
		&i.TotalDislikes,
		&i.TotalVideos,
	)
	return i, err
}

const listChannelVideoStats = `-- name: ListChannelVideoStats :many
SELECT id, title, views_count, likes_count, dislikes_count, uploaded_at
FROM videos
WHERE channel_id = $1
ORDER BY views_count DESC
LIMIT $2 OFFSET $3
`

type ListChannelVideoStatsParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

type ListChannelVideoStatsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	ViewsCount    pgtype.Int8        `db:"views_count" json:"views_count"`
	LikesCount    pgtype.Int8        `db:"likes_count" json:"likes_count"`
	DislikesCount pgtype.Int8        `db:"dislikes_count" json:"dislikes_count"`
	UploadedAt    pgtype.Timestamptz `db:"uploaded_at" json:"uploaded_at"`
}

func (q *Queries) ListChannelVideoStats(ctx context.Context, arg ListChannelVideoStatsParams) ([]ListChannelVideoStatsRow, error) {
	rows, err := q.db.Query(ctx, listChannelVideoStats, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelVideoStatsRow
	for rows.Next() {
		var i ListChannelVideoStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
