// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: caption.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCaption = `-- name: CreateCaption :one
INSERT INTO video_captions (video_id, language, label, url, is_default)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, video_id, language, label, url, is_default, created_at
`

type CreateCaptionParams struct {
	VideoID   pgtype.UUID `db:"video_id" json:"video_id"`
	Language  string      `db:"language" json:"language"`
	Label     string      `db:"label" json:"label"`
	Url       string      `db:"url" json:"url"`
	IsDefault pgtype.Bool `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateCaption(ctx context.Context, arg CreateCaptionParams) (VideoCaption, error) {
	row := q.db.QueryRow(ctx, createCaption,
		arg.VideoID,
		arg.Language,
		arg.Label,
		arg.Url,
		arg.IsDefault,
	)
	var i VideoCaption
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Label,
		&i.Url,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCaption = `-- name: DeleteCaption :exec
DELETE FROM video_captions WHERE id = $1
`

func (q *Queries) DeleteCaption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCaption, id)
	return err
}

const getCaptionByID = `-- name: GetCaptionByID :one
SELECT id, video_id, language, label, url, is_default, created_at FROM video_captions WHERE id = $1
`

func (q *Queries) GetCaptionByID(ctx context.Context, id uuid.UUID) (VideoCaption, error) {
	row := q.db.QueryRow(ctx, getCaptionByID, id)
	var i VideoCaption
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Label,
		&i.Url,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listCaptionsByVideo = `-- name: ListCaptionsByVideo :many
SELECT id, video_id, language, label, url, is_default, created_at FROM video_captions WHERE video_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCaptionsByVideo(ctx context.Context, videoID pgtype.UUID) ([]VideoCaption, error) {
	rows, err := q.db.Query(ctx, listCaptionsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoCaption
	for rows.Next() {
		var i VideoCaption
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Language,
			&i.Label,
			&i.Url,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
