// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (user_id, handle, name, description, avatar_url, banner_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, handle, name, description, avatar_url, banner_url, subscriber_count, created_at, updated_at
`

type CreateChannelParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Handle      string      `db:"handle" json:"handle"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
	BannerUrl   pgtype.Text `db:"banner_url" json:"banner_url"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.UserID,
		arg.Handle,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.BannerUrl,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Handle,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.BannerUrl,
		&i.SubscriberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByHandle = `-- name: GetChannelByHandle :one
SELECT id, user_id, handle, name, description, avatar_url, banner_url, subscriber_count, created_at, updated_at FROM channels WHERE handle = $1
`

func (q *Queries) GetChannelByHandle(ctx context.Context, handle string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByHandle, handle)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Handle,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.BannerUrl,
		&i.SubscriberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, user_id, handle, name, description, avatar_url, banner_url, subscriber_count, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Handle,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.BannerUrl,
		&i.SubscriberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByUserID = `-- name: GetChannelByUserID :one
SELECT id, user_id, handle, name, description, avatar_url, banner_url, subscriber_count, created_at, updated_at FROM channels WHERE user_id = $1 ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetChannelByUserID(ctx context.Context, userID pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByUserID, userID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Handle,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.BannerUrl,
		&i.SubscriberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $2,
    description = $3,
    avatar_url = $4,
    banner_url = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, handle, name, description, avatar_url, banner_url, subscriber_count, created_at, updated_at
`

type UpdateChannelParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	AvatarUrl   pgtype.Text `db:"avatar_url" json:"avatar_url"`
	BannerUrl   pgtype.Text `db:"banner_url" json:"banner_url"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.BannerUrl,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Handle,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.BannerUrl,
		&i.SubscriberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
