// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapter.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO video_chapters (video_id, title, start_seconds)
VALUES ($1, $2, $3)
RETURNING id, video_id, title, start_seconds, created_at
`

type CreateChapterParams struct {
	VideoID      pgtype.UUID `db:"video_id" json:"video_id"`
	Title        string      `db:"title" json:"title"`
	StartSeconds int32       `db:"start_seconds" json:"start_seconds"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (VideoChapter, error) {
	row := q.db.QueryRow(ctx, createChapter, arg.VideoID, arg.Title, arg.StartSeconds)
	var i VideoChapter
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.StartSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM video_chapters WHERE id = $1
`

func (q *Queries) DeleteChapter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapter, id)
	return err
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT id, video_id, title, start_seconds, created_at FROM video_chapters WHERE id = $1
`

func (q *Queries) GetChapterByID(ctx context.Context, id uuid.UUID) (VideoChapter, error) {
	row := q.db.QueryRow(ctx, getChapterByID, id)
	var i VideoChapter
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.StartSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const listChaptersByVideo = `-- name: ListChaptersByVideo :many
SELECT id, video_id, title, start_seconds, created_at FROM video_chapters WHERE video_id = $1 ORDER BY start_seconds ASC
`

func (q *Queries) ListChaptersByVideo(ctx context.Context, videoID pgtype.UUID) ([]VideoChapter, error) {
	rows, err := q.db.Query(ctx, listChaptersByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoChapter
	for rows.Next() {
		var i VideoChapter
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.StartSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
