// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (video_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, video_id, user_id, parent_id, content, likes_count, is_deleted, created_at, updated_at
`

type CreateCommentParams struct {
	VideoID pgtype.UUID `db:"video_id" json:"video_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Content string      `db:"content" json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.VideoID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.LikesCount,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE comments SET is_deleted = true, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, video_id, user_id, parent_id, content, likes_count, is_deleted, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.LikesCount,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByVideo = `-- name: ListCommentsByVideo :many
SELECT comments.id, comments.video_id, comments.user_id, comments.parent_id, comments.content, comments.likes_count, comments.is_deleted, comments.created_at, comments.updated_at, users.id, users.username, users.email, users.display_name, users.bio, users.avatar_url, users.role, users.is_active, users.password_hash, users.created_at, users.updated_at, users.deleted_at, users.deleted_by
FROM comments
JOIN users ON users.id = comments.user_id
WHERE comments.video_id = $1 AND comments.is_deleted = false
ORDER BY comments.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByVideoParams struct {
	VideoID pgtype.UUID `db:"video_id" json:"video_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListCommentsByVideoRow struct {
	Comment Comment `db:"comment" json:"comment"`
	User    User    `db:"user" json:"user"`
}

func (q *Queries) ListCommentsByVideo(ctx context.Context, arg ListCommentsByVideoParams) ([]ListCommentsByVideoRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByVideo, arg.VideoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByVideoRow
	for rows.Next() {
		var i ListCommentsByVideoRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.VideoID,
			&i.Comment.UserID,
			&i.Comment.ParentID,
			&i.Comment.Content,
			&i.Comment.LikesCount,
			&i.Comment.IsDeleted,
			&i.Comment.CreatedAt,
			&i.Comment.UpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.IsActive,
			&i.User.PasswordHash,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.User.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
