// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community_post.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommunityPost = `-- name: CreateCommunityPost :one
INSERT INTO community_posts (channel_id, content, image_url)
VALUES ($1, $2, $3)
RETURNING id, channel_id, content, image_url, likes_count, created_at, updated_at
`

type CreateCommunityPostParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Content   string      `db:"content" json:"content"`
	ImageUrl  pgtype.Text `db:"image_url" json:"image_url"`
}

func (q *Queries) CreateCommunityPost(ctx context.Context, arg CreateCommunityPostParams) (CommunityPost, error) {
	row := q.db.QueryRow(ctx, createCommunityPost, arg.ChannelID, arg.Content, arg.ImageUrl)
	var i CommunityPost
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Content,
		&i.ImageUrl,
		&i.LikesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommunityPostLike = `-- name: CreateCommunityPostLike :exec
INSERT INTO community_post_likes (post_id, user_id) VALUES ($1, $2)
`

type CreateCommunityPostLikeParams struct {
	PostID uuid.UUID `db:"post_id" json:"post_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateCommunityPostLike(ctx context.Context, arg CreateCommunityPostLikeParams) error {
	_, err := q.db.Exec(ctx, createCommunityPostLike, arg.PostID, arg.UserID)
	return err
}

const decrementCommunityPostLikes = `-- name: DecrementCommunityPostLikes :one
UPDATE community_posts SET likes_count = likes_count - 1 WHERE id = $1 RETURNING id, channel_id, content, image_url, likes_count, created_at, updated_at
`

func (q *Queries) DecrementCommunityPostLikes(ctx context.Context, id uuid.UUID) (CommunityPost, error) {
	row := q.db.QueryRow(ctx, decrementCommunityPostLikes, id)
	var i CommunityPost
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Content,
		&i.ImageUrl,
		&i.LikesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommunityPost = `-- name: DeleteCommunityPost :exec
DELETE FROM community_posts WHERE id = $1
`

func (q *Queries) DeleteCommunityPost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommunityPost, id)
	return err
}

const deleteCommunityPostLike = `-- name: DeleteCommunityPostLike :exec
DELETE FROM community_post_likes WHERE post_id = $1 AND user_id = $2
`

type DeleteCommunityPostLikeParams struct {
	PostID uuid.UUID `db:"post_id" json:"post_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteCommunityPostLike(ctx context.Context, arg DeleteCommunityPostLikeParams) error {
	_, err := q.db.Exec(ctx, deleteCommunityPostLike, arg.PostID, arg.UserID)
	return err
}

const getCommunityPostByID = `-- name: GetCommunityPostByID :one
SELECT id, channel_id, content, image_url, likes_count, created_at, updated_at FROM community_posts WHERE id = $1
`

func (q *Queries) GetCommunityPostByID(ctx context.Context, id uuid.UUID) (CommunityPost, error) {
	row := q.db.QueryRow(ctx, getCommunityPostByID, id)
	var i CommunityPost
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Content,
		&i.ImageUrl,
		&i.LikesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommunityPostLike = `-- name: GetCommunityPostLike :one
SELECT post_id, user_id, created_at FROM community_post_likes WHERE post_id = $1 AND user_id = $2
`

type GetCommunityPostLikeParams struct {
	PostID uuid.UUID `db:"post_id" json:"post_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCommunityPostLike(ctx context.Context, arg GetCommunityPostLikeParams) (CommunityPostLike, error) {
	row := q.db.QueryRow(ctx, getCommunityPostLike, arg.PostID, arg.UserID)
	var i CommunityPostLike
	err := row.Scan(&i.PostID, &i.UserID, &i.CreatedAt)
	return i, err
}

const incrementCommunityPostLikes = `-- name: IncrementCommunityPostLikes :one
UPDATE community_posts SET likes_count = likes_count + 1 WHERE id = $1 RETURNING id, channel_id, content, image_url, likes_count, created_at, updated_at
`

func (q *Queries) IncrementCommunityPostLikes(ctx context.Context, id uuid.UUID) (CommunityPost, error) {
	row := q.db.QueryRow(ctx, incrementCommunityPostLikes, id)
	var i CommunityPost
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Content,
		&i.ImageUrl,
		&i.LikesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommunityPostsByChannel = `-- name: ListCommunityPostsByChannel :many
SELECT id, channel_id, content, image_url, likes_count, created_at, updated_at FROM community_posts
WHERE channel_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommunityPostsByChannelParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListCommunityPostsByChannel(ctx context.Context, arg ListCommunityPostsByChannelParams) ([]CommunityPost, error) {
	rows, err := q.db.Query(ctx, listCommunityPostsByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityPost
	for rows.Next() {
		var i CommunityPost
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Content,
			&i.ImageUrl,
			&i.LikesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
