// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: end_screen.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEndScreen = `-- name: CreateEndScreen :one
INSERT INTO video_end_screens (video_id, type, target_id, start_seconds, position_x, position_y)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, video_id, type, target_id, start_seconds, position_x, position_y, created_at
`

type CreateEndScreenParams struct {
	VideoID      uuid.UUID `db:"video_id" json:"video_id"`
	Type         string    `db:"type" json:"type"`
	TargetID     uuid.UUID `db:"target_id" json:"target_id"`
	StartSeconds int32     `db:"start_seconds" json:"start_seconds"`
	PositionX    float32   `db:"position_x" json:"position_x"`
	PositionY    float32   `db:"position_y" json:"position_y"`
}

func (q *Queries) CreateEndScreen(ctx context.Context, arg CreateEndScreenParams) (VideoEndScreen, error) {
	row := q.db.QueryRow(ctx, createEndScreen,
		arg.VideoID,
		arg.Type,
		arg.TargetID,
		arg.StartSeconds,
		arg.PositionX,
		arg.PositionY,
	)
	var i VideoEndScreen
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.TargetID,
		&i.StartSeconds,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndScreen = `-- name: DeleteEndScreen :exec
DELETE FROM video_end_screens WHERE id = $1
`

func (q *Queries) DeleteEndScreen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndScreen, id)
	return err
}

const getEndScreenByID = `-- name: GetEndScreenByID :one
SELECT id, video_id, type, target_id, start_seconds, position_x, position_y, created_at FROM video_end_screens WHERE id = $1
`

func (q *Queries) GetEndScreenByID(ctx context.Context, id uuid.UUID) (VideoEndScreen, error) {
	row := q.db.QueryRow(ctx, getEndScreenByID, id)
	var i VideoEndScreen
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Type,
		&i.TargetID,
		&i.StartSeconds,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
	)
	return i, err
}

const listEndScreensByVideo = `-- name: ListEndScreensByVideo :many
SELECT id, video_id, type, target_id, start_seconds, position_x, position_y, created_at FROM video_end_screens
WHERE video_id = $1
ORDER BY start_seconds ASC
`

func (q *Queries) ListEndScreensByVideo(ctx context.Context, videoID uuid.UUID) ([]VideoEndScreen, error) {
	rows, err := q.db.Query(ctx, listEndScreensByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoEndScreen
	for rows.Next() {
		var i VideoEndScreen
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Type,
			&i.TargetID,
			&i.StartSeconds,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
