// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_stream.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLiveStreamByChannelID = `-- name: GetLiveStreamByChannelID :one
SELECT id, channel_id, stream_key, title, status, started_at, created_at, updated_at FROM live_streams WHERE channel_id = $1
`

func (q *Queries) GetLiveStreamByChannelID(ctx context.Context, channelID pgtype.UUID) (LiveStream, error) {
	row := q.db.QueryRow(ctx, getLiveStreamByChannelID, channelID)
	var i LiveStream
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StreamKey,
		&i.Title,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveStreams = `-- name: ListLiveStreams :many
SELECT id, channel_id, stream_key, title, status, started_at, created_at, updated_at FROM live_streams
`

// Small table (one row per channel that's ever gone live) — a full scan
// every poll interval is cheap enough that indexing by status isn't needed.
func (q *Queries) ListLiveStreams(ctx context.Context) ([]LiveStream, error) {
	rows, err := q.db.Query(ctx, listLiveStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveStream
	for rows.Next() {
		var i LiveStream
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.StreamKey,
			&i.Title,
			&i.Status,
			&i.StartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLiveStreamStatus = `-- name: SetLiveStreamStatus :exec
UPDATE live_streams SET status = $2, started_at = $3, updated_at = NOW() WHERE id = $1
`

type SetLiveStreamStatusParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Status    string             `db:"status" json:"status"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) SetLiveStreamStatus(ctx context.Context, arg SetLiveStreamStatusParams) error {
	_, err := q.db.Exec(ctx, setLiveStreamStatus, arg.ID, arg.Status, arg.StartedAt)
	return err
}

const updateLiveStreamTitle = `-- name: UpdateLiveStreamTitle :one
UPDATE live_streams SET title = $2, updated_at = NOW() WHERE channel_id = $1 RETURNING id, channel_id, stream_key, title, status, started_at, created_at, updated_at
`

type UpdateLiveStreamTitleParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Title     string      `db:"title" json:"title"`
}

func (q *Queries) UpdateLiveStreamTitle(ctx context.Context, arg UpdateLiveStreamTitleParams) (LiveStream, error) {
	row := q.db.QueryRow(ctx, updateLiveStreamTitle, arg.ChannelID, arg.Title)
	var i LiveStream
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StreamKey,
		&i.Title,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLiveStreamKey = `-- name: UpsertLiveStreamKey :one
INSERT INTO live_streams (channel_id, stream_key)
VALUES ($1, $2)
ON CONFLICT (channel_id) DO UPDATE
SET stream_key = $2, status = 'offline', started_at = NULL, updated_at = NOW()
RETURNING id, channel_id, stream_key, title, status, started_at, created_at, updated_at
`

type UpsertLiveStreamKeyParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	StreamKey string      `db:"stream_key" json:"stream_key"`
}

// Issuing a key is also how a channel "resets" their stream — regenerating
// forces status back to offline until the new key is actually used to publish.
func (q *Queries) UpsertLiveStreamKey(ctx context.Context, arg UpsertLiveStreamKeyParams) (LiveStream, error) {
	row := q.db.QueryRow(ctx, upsertLiveStreamKey, arg.ChannelID, arg.StreamKey)
	var i LiveStream
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StreamKey,
		&i.Title,
		&i.Status,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
