// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Channel struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	Handle          string             `db:"handle" json:"handle"`
	Name            string             `db:"name" json:"name"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	BannerUrl       pgtype.Text        `db:"banner_url" json:"banner_url"`
	SubscriberCount pgtype.Int8        `db:"subscriber_count" json:"subscriber_count"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Comment struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	VideoID    pgtype.UUID        `db:"video_id" json:"video_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	ParentID   pgtype.UUID        `db:"parent_id" json:"parent_id"`
	Content    string             `db:"content" json:"content"`
	LikesCount pgtype.Int8        `db:"likes_count" json:"likes_count"`
	IsDeleted  pgtype.Bool        `db:"is_deleted" json:"is_deleted"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CommentLike struct {
	CommentID uuid.UUID          `db:"comment_id" json:"comment_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CommunityPost struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ChannelID  pgtype.UUID        `db:"channel_id" json:"channel_id"`
	Content    string             `db:"content" json:"content"`
	ImageUrl   pgtype.Text        `db:"image_url" json:"image_url"`
	LikesCount pgtype.Int8        `db:"likes_count" json:"likes_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CommunityPostLike struct {
	PostID    uuid.UUID          `db:"post_id" json:"post_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LiveStream struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ChannelID pgtype.UUID        `db:"channel_id" json:"channel_id"`
	StreamKey string             `db:"stream_key" json:"stream_key"`
	Title     string             `db:"title" json:"title"`
	Status    string             `db:"status" json:"status"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Notification struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Type      string             `db:"type" json:"type"`
	ActorID   pgtype.UUID        `db:"actor_id" json:"actor_id"`
	VideoID   pgtype.UUID        `db:"video_id" json:"video_id"`
	CommentID pgtype.UUID        `db:"comment_id" json:"comment_id"`
	IsRead    pgtype.Bool        `db:"is_read" json:"is_read"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Playlist struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	ChannelID   pgtype.UUID        `db:"channel_id" json:"channel_id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	IsPublic    pgtype.Bool        `db:"is_public" json:"is_public"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PlaylistVideo struct {
	PlaylistID uuid.UUID          `db:"playlist_id" json:"playlist_id"`
	VideoID    uuid.UUID          `db:"video_id" json:"video_id"`
	Position   int32              `db:"position" json:"position"`
	AddedAt    pgtype.Timestamptz `db:"added_at" json:"added_at"`
}

type Report struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	ReporterID  pgtype.UUID        `db:"reporter_id" json:"reporter_id"`
	VideoID     pgtype.UUID        `db:"video_id" json:"video_id"`
	CommentID   pgtype.UUID        `db:"comment_id" json:"comment_id"`
	Reason      string             `db:"reason" json:"reason"`
	Status      pgtype.Text        `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ActionTaken pgtype.Text        `db:"action_taken" json:"action_taken"`
	ResolvedBy  pgtype.UUID        `db:"resolved_by" json:"resolved_by"`
}

type Session struct {
	TokenHash string             `db:"token_hash" json:"token_hash"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Subscription struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ChannelID pgtype.UUID        `db:"channel_id" json:"channel_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Username        string             `db:"username" json:"username"`
	Email           string             `db:"email" json:"email"`
	DisplayName     pgtype.Text        `db:"display_name" json:"display_name"`
	Bio             pgtype.Text        `db:"bio" json:"bio"`
	AvatarUrl       pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Role            UserRole           `db:"role" json:"role"`
	IsActive        pgtype.Bool        `db:"is_active" json:"is_active"`
	PasswordHash    string             `db:"password_hash" json:"password_hash"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy       pgtype.UUID        `db:"deleted_by" json:"deleted_by"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
}

type Video struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ChannelID      pgtype.UUID        `db:"channel_id" json:"channel_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Status         string             `db:"status" json:"status"`
	Visibility     string             `db:"visibility" json:"visibility"`
	ViewsCount     pgtype.Int8        `db:"views_count" json:"views_count"`
	LikesCount     pgtype.Int8        `db:"likes_count" json:"likes_count"`
	DislikesCount  pgtype.Int8        `db:"dislikes_count" json:"dislikes_count"`
	ThumbnailUrl   pgtype.Text        `db:"thumbnail_url" json:"thumbnail_url"`
	OriginalUrl    pgtype.Text        `db:"original_url" json:"original_url"`
	HlsPlaylistUrl pgtype.Text        `db:"hls_playlist_url" json:"hls_playlist_url"`
	Category       pgtype.Text        `db:"category" json:"category"`
	Tags           []string           `db:"tags" json:"tags"`
	UploadedAt     pgtype.Timestamptz `db:"uploaded_at" json:"uploaded_at"`
	PublishedAt    pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Duration       pgtype.Int4        `db:"duration" json:"duration"`
	IsShort        bool               `db:"is_short" json:"is_short"`
}

type VideoCaption struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	VideoID   pgtype.UUID        `db:"video_id" json:"video_id"`
	Language  string             `db:"language" json:"language"`
	Label     string             `db:"label" json:"label"`
	Url       string             `db:"url" json:"url"`
	IsDefault pgtype.Bool        `db:"is_default" json:"is_default"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VideoChapter struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	VideoID      pgtype.UUID        `db:"video_id" json:"video_id"`
	Title        string             `db:"title" json:"title"`
	StartSeconds int32              `db:"start_seconds" json:"start_seconds"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VideoEndScreen struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	VideoID      uuid.UUID          `db:"video_id" json:"video_id"`
	Type         string             `db:"type" json:"type"`
	TargetID     uuid.UUID          `db:"target_id" json:"target_id"`
	StartSeconds int32              `db:"start_seconds" json:"start_seconds"`
	PositionX    float32            `db:"position_x" json:"position_x"`
	PositionY    float32            `db:"position_y" json:"position_y"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VideoFile struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	VideoID    pgtype.UUID        `db:"video_id" json:"video_id"`
	Resolution string             `db:"resolution" json:"resolution"`
	Url        string             `db:"url" json:"url"`
	FileSize   pgtype.Int8        `db:"file_size" json:"file_size"`
	Bitrate    pgtype.Int4        `db:"bitrate" json:"bitrate"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VideoInteraction struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	VideoID   pgtype.UUID        `db:"video_id" json:"video_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Type      string             `db:"type" json:"type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VideoSearch struct {
	VideoID      uuid.UUID   `db:"video_id" json:"video_id"`
	SearchVector interface{} `db:"search_vector" json:"search_vector"`
}

type WatchHistory struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	VideoID   pgtype.UUID        `db:"video_id" json:"video_id"`
	WatchedAt pgtype.Timestamptz `db:"watched_at" json:"watched_at"`
	Progress  pgtype.Int4        `db:"progress" json:"progress"`
	Completed pgtype.Bool        `db:"completed" json:"completed"`
}

type WatchLater struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	VideoID   uuid.UUID          `db:"video_id" json:"video_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
