// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, actor_id, video_id, comment_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, actor_id, video_id, comment_id, is_read, created_at
`

type CreateNotificationParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	Type      string      `db:"type" json:"type"`
	ActorID   pgtype.UUID `db:"actor_id" json:"actor_id"`
	VideoID   pgtype.UUID `db:"video_id" json:"video_id"`
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.ActorID,
		arg.VideoID,
		arg.CommentID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ActorID,
		&i.VideoID,
		&i.CommentID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT
    notifications.id, notifications.type, notifications.video_id, notifications.comment_id,
    notifications.is_read, notifications.created_at,
    actor.username AS actor_username,
    videos.title AS video_title
FROM notifications
LEFT JOIN users actor ON actor.id = notifications.actor_id
LEFT JOIN videos ON videos.id = notifications.video_id
WHERE notifications.user_id = $1
ORDER BY notifications.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type ListNotificationsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Type          string             `db:"type" json:"type"`
	VideoID       pgtype.UUID        `db:"video_id" json:"video_id"`
	CommentID     pgtype.UUID        `db:"comment_id" json:"comment_id"`
	IsRead        pgtype.Bool        `db:"is_read" json:"is_read"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ActorUsername pgtype.Text        `db:"actor_username" json:"actor_username"`
	VideoTitle    pgtype.Text        `db:"video_title" json:"video_title"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.VideoID,
			&i.CommentID,
			&i.IsRead,
			&i.CreatedAt,
			&i.ActorUsername,
			&i.VideoTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET is_read = true WHERE id = $1 AND user_id = $2 RETURNING id, user_id, type, actor_id, video_id, comment_id, is_read, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ActorID,
		&i.VideoID,
		&i.CommentID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
