// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addVideoToPlaylist = `-- name: AddVideoToPlaylist :one
INSERT INTO playlist_videos (playlist_id, video_id, position)
VALUES ($1, $2, COALESCE((SELECT MAX(position) + 1 FROM playlist_videos WHERE playlist_id = $1), 0))
RETURNING playlist_id, video_id, position, added_at
`

type AddVideoToPlaylistParams struct {
	PlaylistID uuid.UUID `db:"playlist_id" json:"playlist_id"`
	VideoID    uuid.UUID `db:"video_id" json:"video_id"`
}

func (q *Queries) AddVideoToPlaylist(ctx context.Context, arg AddVideoToPlaylistParams) (PlaylistVideo, error) {
	row := q.db.QueryRow(ctx, addVideoToPlaylist, arg.PlaylistID, arg.VideoID)
	var i PlaylistVideo
	err := row.Scan(
		&i.PlaylistID,
		&i.VideoID,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (channel_id, name, description, is_public)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, name, description, is_public, created_at, updated_at
`

type CreatePlaylistParams struct {
	ChannelID   pgtype.UUID `db:"channel_id" json:"channel_id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	IsPublic    pgtype.Bool `db:"is_public" json:"is_public"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.ChannelID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlaylist, id)
	return err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, channel_id, name, description, is_public, created_at, updated_at FROM playlists WHERE id = $1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id uuid.UUID) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlaylistsByChannel = `-- name: ListAllPlaylistsByChannel :many
SELECT id, channel_id, name, description, is_public, created_at, updated_at FROM playlists
WHERE channel_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllPlaylistsByChannelParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

// Same as ListPlaylistsByChannel but includes private playlists — only
// meant to be used once the caller is confirmed as the channel's owner.
func (q *Queries) ListAllPlaylistsByChannel(ctx context.Context, arg ListAllPlaylistsByChannelParams) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, listAllPlaylistsByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistVideos = `-- name: ListPlaylistVideos :many
SELECT videos.id, videos.channel_id, videos.title, videos.description, videos.status, videos.visibility, videos.views_count, videos.likes_count, videos.dislikes_count, videos.thumbnail_url, videos.original_url, videos.hls_playlist_url, videos.category, videos.tags, videos.uploaded_at, videos.published_at, videos.created_at, videos.updated_at, videos.duration, videos.is_short
FROM playlist_videos
JOIN videos ON videos.id = playlist_videos.video_id
WHERE playlist_videos.playlist_id = $1
ORDER BY playlist_videos.position ASC
`

func (q *Queries) ListPlaylistVideos(ctx context.Context, playlistID uuid.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listPlaylistVideos, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByChannel = `-- name: ListPlaylistsByChannel :many
SELECT id, channel_id, name, description, is_public, created_at, updated_at FROM playlists
WHERE channel_id = $1 AND is_public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlaylistsByChannelParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListPlaylistsByChannel(ctx context.Context, arg ListPlaylistsByChannelParams) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVideoFromPlaylist = `-- name: RemoveVideoFromPlaylist :exec
DELETE FROM playlist_videos WHERE playlist_id = $1 AND video_id = $2
`

type RemoveVideoFromPlaylistParams struct {
	PlaylistID uuid.UUID `db:"playlist_id" json:"playlist_id"`
	VideoID    uuid.UUID `db:"video_id" json:"video_id"`
}

func (q *Queries) RemoveVideoFromPlaylist(ctx context.Context, arg RemoveVideoFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeVideoFromPlaylist, arg.PlaylistID, arg.VideoID)
	return err
}
