// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdjustVideoReactionCounts(ctx context.Context, arg AdjustVideoReactionCountsParams) (Video, error)
	// ==================== ADMIN QUERIES ====================
	AdminDeleteUser(ctx context.Context, arg AdminDeleteUserParams) error
	AdminGetAllUsers(ctx context.Context, arg AdminGetAllUsersParams) ([]User, error)
	AdminGetUserWithDeleted(ctx context.Context, id uuid.UUID) (User, error)
	// Optional useful admin queries:
	AdminUpdateUserRole(ctx context.Context, arg AdminUpdateUserRoleParams) (User, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVideoInteraction(ctx context.Context, arg CreateVideoInteractionParams) (VideoInteraction, error)
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error)
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	DeleteVideoInteraction(ctx context.Context, arg DeleteVideoInteractionParams) error
	GetChannelByHandle(ctx context.Context, handle string) (Channel, error)
	GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error)
	GetChannelByUserID(ctx context.Context, userID pgtype.UUID) (Channel, error)
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRole(ctx context.Context, id uuid.UUID) (UserRole, error)
	GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error)
	GetVideoInteraction(ctx context.Context, arg GetVideoInteractionParams) (VideoInteraction, error)
	IncrementVideoDislikes(ctx context.Context, id uuid.UUID) (Video, error)
	IncrementVideoLikes(ctx context.Context, id uuid.UUID) (Video, error)
	IncrementVideoViews(ctx context.Context, id uuid.UUID) (Video, error)
	ListPublicVideos(ctx context.Context, arg ListPublicVideosParams) ([]Video, error)
	ListVideosByChannel(ctx context.Context, arg ListVideosByChannelParams) ([]Video, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVideoInteractionType(ctx context.Context, arg UpdateVideoInteractionTypeParams) (VideoInteraction, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
