// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListReports = `-- name: AdminListReports :many
SELECT
    reports.id, reports.reporter_id, reports.video_id, reports.comment_id, reports.reason, reports.status, reports.created_at,
    u.username AS reporter_username,
    v.title AS video_title,
    c.content AS comment_content
FROM reports
JOIN users u ON u.id = reports.reporter_id
LEFT JOIN videos v ON v.id = reports.video_id
LEFT JOIN comments c ON c.id = reports.comment_id
ORDER BY reports.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListReportsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type AdminListReportsRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ReporterID       pgtype.UUID        `db:"reporter_id" json:"reporter_id"`
	VideoID          pgtype.UUID        `db:"video_id" json:"video_id"`
	CommentID        pgtype.UUID        `db:"comment_id" json:"comment_id"`
	Reason           string             `db:"reason" json:"reason"`
	Status           pgtype.Text        `db:"status" json:"status"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ReporterUsername string             `db:"reporter_username" json:"reporter_username"`
	VideoTitle       pgtype.Text        `db:"video_title" json:"video_title"`
	CommentContent   pgtype.Text        `db:"comment_content" json:"comment_content"`
}

func (q *Queries) AdminListReports(ctx context.Context, arg AdminListReportsParams) ([]AdminListReportsRow, error) {
	rows, err := q.db.Query(ctx, adminListReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListReportsRow
	for rows.Next() {
		var i AdminListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.VideoID,
			&i.CommentID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.ReporterUsername,
			&i.VideoTitle,
			&i.CommentContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateReportStatus = `-- name: AdminUpdateReportStatus :one
UPDATE reports SET status = $2 WHERE id = $1 RETURNING id, reporter_id, video_id, comment_id, reason, status, created_at
`

type AdminUpdateReportStatusParams struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	Status pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) AdminUpdateReportStatus(ctx context.Context, arg AdminUpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, adminUpdateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.VideoID,
		&i.CommentID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, video_id, comment_id, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, reporter_id, video_id, comment_id, reason, status, created_at
`

type CreateReportParams struct {
	ReporterID pgtype.UUID `db:"reporter_id" json:"reporter_id"`
	VideoID    pgtype.UUID `db:"video_id" json:"video_id"`
	CommentID  pgtype.UUID `db:"comment_id" json:"comment_id"`
	Reason     string      `db:"reason" json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.VideoID,
		arg.CommentID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.VideoID,
		&i.CommentID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
