// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash string             `db:"token_hash" json:"token_hash"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT sessions.token_hash, sessions.user_id, sessions.created_at, sessions.expires_at, users.id, users.username, users.email, users.display_name, users.bio, users.avatar_url, users.role, users.is_active, users.password_hash, users.created_at, users.updated_at, users.deleted_at, users.deleted_by, users.email_verified_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > NOW()
  AND users.deleted_at IS NULL
`

type GetSessionWithUserRow struct {
	Session Session `db:"session" json:"session"`
	User    User    `db:"user" json:"user"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Session.TokenHash,
		&i.Session.UserID,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.Bio,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.IsActive,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.User.DeletedBy,
		&i.User.EmailVerifiedAt,
	)
	return i, err
}
