// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustChannelSubscriberCount = `-- name: AdjustChannelSubscriberCount :one
UPDATE channels
SET subscriber_count = subscriber_count + $1::bigint
WHERE id = $2
RETURNING id, user_id, handle, name, description, avatar_url, banner_url, subscriber_count, created_at, updated_at
`

type AdjustChannelSubscriberCountParams struct {
	Delta int64     `db:"delta" json:"delta"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) AdjustChannelSubscriberCount(ctx context.Context, arg AdjustChannelSubscriberCountParams) (Channel, error) {
	row := q.db.QueryRow(ctx, adjustChannelSubscriberCount, arg.Delta, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Handle,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.BannerUrl,
		&i.SubscriberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (channel_id, user_id) VALUES ($1, $2) RETURNING id, channel_id, user_id, created_at
`

type CreateSubscriptionParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.ChannelID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE channel_id = $1 AND user_id = $2
`

type DeleteSubscriptionParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.ChannelID, arg.UserID)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, channel_id, user_id, created_at FROM subscriptions WHERE channel_id = $1 AND user_id = $2
`

type GetSubscriptionParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.ChannelID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listSubscriptionFeed = `-- name: ListSubscriptionFeed :many
SELECT videos.id, videos.channel_id, videos.title, videos.description, videos.status, videos.visibility, videos.views_count, videos.likes_count, videos.dislikes_count, videos.thumbnail_url, videos.original_url, videos.hls_playlist_url, videos.category, videos.tags, videos.uploaded_at, videos.published_at, videos.created_at, videos.updated_at, videos.duration, videos.is_short
FROM videos
JOIN subscriptions ON subscriptions.channel_id = videos.channel_id
WHERE subscriptions.user_id = $1
  AND videos.visibility = 'public'
  AND videos.status = 'ready'
ORDER BY videos.uploaded_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscriptionFeedParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListSubscriptionFeed(ctx context.Context, arg ListSubscriptionFeedParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listSubscriptionFeed, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
