// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_interaction.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustVideoReactionCounts = `-- name: AdjustVideoReactionCounts :one
UPDATE videos
SET likes_count = likes_count + $1::bigint,
    dislikes_count = dislikes_count + $2::bigint
WHERE id = $3
RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration
`

type AdjustVideoReactionCountsParams struct {
	LikesDelta    int64     `db:"likes_delta" json:"likes_delta"`
	DislikesDelta int64     `db:"dislikes_delta" json:"dislikes_delta"`
	ID            uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) AdjustVideoReactionCounts(ctx context.Context, arg AdjustVideoReactionCountsParams) (Video, error) {
	row := q.db.QueryRow(ctx, adjustVideoReactionCounts, arg.LikesDelta, arg.DislikesDelta, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}

const createVideoInteraction = `-- name: CreateVideoInteraction :one
INSERT INTO video_interactions (video_id, user_id, type) VALUES ($1, $2, $3) RETURNING id, video_id, user_id, type, created_at
`

type CreateVideoInteractionParams struct {
	VideoID pgtype.UUID `db:"video_id" json:"video_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Type    string      `db:"type" json:"type"`
}

func (q *Queries) CreateVideoInteraction(ctx context.Context, arg CreateVideoInteractionParams) (VideoInteraction, error) {
	row := q.db.QueryRow(ctx, createVideoInteraction, arg.VideoID, arg.UserID, arg.Type)
	var i VideoInteraction
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVideoInteraction = `-- name: DeleteVideoInteraction :exec
DELETE FROM video_interactions WHERE video_id = $1 AND user_id = $2
`

type DeleteVideoInteractionParams struct {
	VideoID pgtype.UUID `db:"video_id" json:"video_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteVideoInteraction(ctx context.Context, arg DeleteVideoInteractionParams) error {
	_, err := q.db.Exec(ctx, deleteVideoInteraction, arg.VideoID, arg.UserID)
	return err
}

const getVideoInteraction = `-- name: GetVideoInteraction :one
SELECT id, video_id, user_id, type, created_at FROM video_interactions WHERE video_id = $1 AND user_id = $2
`

type GetVideoInteractionParams struct {
	VideoID pgtype.UUID `db:"video_id" json:"video_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetVideoInteraction(ctx context.Context, arg GetVideoInteractionParams) (VideoInteraction, error) {
	row := q.db.QueryRow(ctx, getVideoInteraction, arg.VideoID, arg.UserID)
	var i VideoInteraction
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const updateVideoInteractionType = `-- name: UpdateVideoInteractionType :one
UPDATE video_interactions SET type = $3 WHERE video_id = $1 AND user_id = $2 RETURNING id, video_id, user_id, type, created_at
`

type UpdateVideoInteractionTypeParams struct {
	VideoID pgtype.UUID `db:"video_id" json:"video_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Type    string      `db:"type" json:"type"`
}

func (q *Queries) UpdateVideoInteractionType(ctx context.Context, arg UpdateVideoInteractionTypeParams) (VideoInteraction, error) {
	row := q.db.QueryRow(ctx, updateVideoInteractionType, arg.VideoID, arg.UserID, arg.Type)
	var i VideoInteraction
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
