// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminDeleteVideo = `-- name: AdminDeleteVideo :exec
DELETE FROM videos WHERE id = $1
`

func (q *Queries) AdminDeleteVideo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteVideo, id)
	return err
}

const adminListVideos = `-- name: AdminListVideos :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type AdminListVideosParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) AdminListVideos(ctx context.Context, arg AdminListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, adminListVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNextPendingVideo = `-- name: ClaimNextPendingVideo :one
UPDATE videos
SET status = 'transcoding'
WHERE id = (
    SELECT id FROM videos
    WHERE status = 'processing'
    ORDER BY uploaded_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

func (q *Queries) ClaimNextPendingVideo(ctx context.Context) (Video, error) {
	row := q.db.QueryRow(ctx, claimNextPendingVideo)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const completeVideoProcessing = `-- name: CompleteVideoProcessing :one
UPDATE videos
SET status = 'ready',
    hls_playlist_url = $2,
    thumbnail_url = COALESCE(NULLIF(thumbnail_url, ''), $3),
    duration = $4,
    is_short = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

type CompleteVideoProcessingParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	HlsPlaylistUrl pgtype.Text `db:"hls_playlist_url" json:"hls_playlist_url"`
	ThumbnailUrl   pgtype.Text `db:"thumbnail_url" json:"thumbnail_url"`
	Duration       pgtype.Int4 `db:"duration" json:"duration"`
	IsShort        bool        `db:"is_short" json:"is_short"`
}

func (q *Queries) CompleteVideoProcessing(ctx context.Context, arg CompleteVideoProcessingParams) (Video, error) {
	row := q.db.QueryRow(ctx, completeVideoProcessing,
		arg.ID,
		arg.HlsPlaylistUrl,
		arg.ThumbnailUrl,
		arg.Duration,
		arg.IsShort,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (channel_id, title, description, duration, status, visibility, category, tags, original_url, thumbnail_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

type CreateVideoParams struct {
	ChannelID    pgtype.UUID `db:"channel_id" json:"channel_id"`
	Title        string      `db:"title" json:"title"`
	Description  pgtype.Text `db:"description" json:"description"`
	Duration     pgtype.Int4 `db:"duration" json:"duration"`
	Status       string      `db:"status" json:"status"`
	Visibility   string      `db:"visibility" json:"visibility"`
	Category     pgtype.Text `db:"category" json:"category"`
	Tags         []string    `db:"tags" json:"tags"`
	OriginalUrl  pgtype.Text `db:"original_url" json:"original_url"`
	ThumbnailUrl pgtype.Text `db:"thumbnail_url" json:"thumbnail_url"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.Duration,
		arg.Status,
		arg.Visibility,
		arg.Category,
		arg.Tags,
		arg.OriginalUrl,
		arg.ThumbnailUrl,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const failVideoProcessing = `-- name: FailVideoProcessing :exec
UPDATE videos SET status = 'failed', updated_at = NOW() WHERE id = $1
`

func (q *Queries) FailVideoProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failVideoProcessing, id)
	return err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos WHERE id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const incrementVideoDislikes = `-- name: IncrementVideoDislikes :one
UPDATE videos SET dislikes_count = dislikes_count + 1 WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

func (q *Queries) IncrementVideoDislikes(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, incrementVideoDislikes, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const incrementVideoLikes = `-- name: IncrementVideoLikes :one
UPDATE videos SET likes_count = likes_count + 1 WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

func (q *Queries) IncrementVideoLikes(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, incrementVideoLikes, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const incrementVideoViews = `-- name: IncrementVideoViews :one
UPDATE videos SET views_count = views_count + 1 WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

func (q *Queries) IncrementVideoViews(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, incrementVideoViews, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}

const listLikedVideosByUser = `-- name: ListLikedVideosByUser :many
SELECT videos.id, videos.channel_id, videos.title, videos.description, videos.status, videos.visibility, videos.views_count, videos.likes_count, videos.dislikes_count, videos.thumbnail_url, videos.original_url, videos.hls_playlist_url, videos.category, videos.tags, videos.uploaded_at, videos.published_at, videos.created_at, videos.updated_at, videos.duration, videos.is_short FROM video_interactions
JOIN videos ON videos.id = video_interactions.video_id
WHERE video_interactions.user_id = $1 AND video_interactions.type = 'like'
ORDER BY video_interactions.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLikedVideosByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListLikedVideosByUser(ctx context.Context, arg ListLikedVideosByUserParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listLikedVideosByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalizedFeed = `-- name: ListPersonalizedFeed :many
WITH watched_categories AS (
    SELECT v.category, COUNT(*) AS watch_count
    FROM watch_history wh
    JOIN videos v ON v.id = wh.video_id
    WHERE wh.user_id = $1 AND v.category != ''
    GROUP BY v.category
)
SELECT v.id, v.channel_id, v.title, v.description, v.status, v.visibility, v.views_count, v.likes_count, v.dislikes_count, v.thumbnail_url, v.original_url, v.hls_playlist_url, v.category, v.tags, v.uploaded_at, v.published_at, v.created_at, v.updated_at, v.duration, v.is_short FROM videos v
LEFT JOIN watched_categories wc ON wc.category = v.category
WHERE v.visibility = 'public' AND v.status = 'ready'
ORDER BY
    (v.channel_id IN (SELECT s.channel_id FROM subscriptions s WHERE s.user_id = $1)) DESC,
    COALESCE(wc.watch_count, 0) DESC,
    v.uploaded_at DESC
LIMIT $2 OFFSET $3
`

type ListPersonalizedFeedParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

// Same recency-ranked pool as ListPublicVideos, boosted by two signals
// already in the schema: subscribed channels and categories the user
// actually watches. No ML model — good enough at this scale, and every
// signal here already has an index (subscriptions.user_id, watch_history.user_id).
func (q *Queries) ListPersonalizedFeed(ctx context.Context, arg ListPersonalizedFeedParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listPersonalizedFeed, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicVideos = `-- name: ListPublicVideos :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos
WHERE visibility = 'public' AND status = 'ready'
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicVideosParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListPublicVideos(ctx context.Context, arg ListPublicVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listPublicVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedVideos = `-- name: ListRelatedVideos :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos
WHERE id != $1
  AND visibility = 'public'
  AND status = 'ready'
  AND (channel_id = $2 OR (category != '' AND category = $3))
ORDER BY (channel_id = $2) DESC, views_count DESC
LIMIT $4
`

type ListRelatedVideosParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Category  pgtype.Text `db:"category" json:"category"`
	Limit     int32       `db:"limit" json:"limit"`
}

// No ML/recommendation model — just same channel first, then same
// category, ranked by views. Good enough at this scale.
func (q *Queries) ListRelatedVideos(ctx context.Context, arg ListRelatedVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listRelatedVideos,
		arg.ID,
		arg.ChannelID,
		arg.Category,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShorts = `-- name: ListShorts :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos
WHERE visibility = 'public' AND status = 'ready' AND is_short = true
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type ListShortsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListShorts(ctx context.Context, arg ListShortsParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listShorts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingVideos = `-- name: ListTrendingVideos :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos
WHERE visibility = 'public' AND status = 'ready'
  AND uploaded_at > NOW() - INTERVAL '7 days'
ORDER BY views_count DESC
LIMIT $1
`

// No view-event log exists (views_count is a running counter), so recency
// is approximated by upload window rather than true view-velocity — good
// enough at this scale, and needs no new schema.
func (q *Queries) ListTrendingVideos(ctx context.Context, limit int32) ([]Video, error) {
	rows, err := q.db.Query(ctx, listTrendingVideos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByChannel = `-- name: ListVideosByChannel :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short FROM videos WHERE channel_id = $1 ORDER BY uploaded_at DESC LIMIT $2 OFFSET $3
`

type ListVideosByChannelParams struct {
	ChannelID pgtype.UUID `db:"channel_id" json:"channel_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListVideosByChannel(ctx context.Context, arg ListVideosByChannelParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVideos = `-- name: SearchVideos :many
SELECT videos.id, videos.channel_id, videos.title, videos.description, videos.status, videos.visibility, videos.views_count, videos.likes_count, videos.dislikes_count, videos.thumbnail_url, videos.original_url, videos.hls_playlist_url, videos.category, videos.tags, videos.uploaded_at, videos.published_at, videos.created_at, videos.updated_at, videos.duration, videos.is_short
FROM videos
JOIN video_search ON video_search.video_id = videos.id
WHERE video_search.search_vector @@ websearch_to_tsquery('english', $1)
  AND videos.visibility = 'public' AND videos.status = 'ready'
ORDER BY ts_rank(video_search.search_vector, websearch_to_tsquery('english', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchVideosParams struct {
	WebsearchToTsquery string `db:"websearch_to_tsquery" json:"websearch_to_tsquery"`
	Limit              int32  `db:"limit" json:"limit"`
	Offset             int32  `db:"offset" json:"offset"`
}

func (q *Queries) SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, searchVideos, arg.WebsearchToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestVideoTitles = `-- name: SuggestVideoTitles :many
SELECT DISTINCT title FROM videos
WHERE visibility = 'public' AND status = 'ready'
  AND lower(title) LIKE lower($1) || '%'
LIMIT 8
`

func (q *Queries) SuggestVideoTitles(ctx context.Context, lower string) ([]string, error) {
	rows, err := q.db.Query(ctx, suggestVideoTitles, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET title = $2,
    description = $3,
    thumbnail_url = $4,
    category = $5,
    tags = $6,
    visibility = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration, is_short
`

type UpdateVideoParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Title        string      `db:"title" json:"title"`
	Description  pgtype.Text `db:"description" json:"description"`
	ThumbnailUrl pgtype.Text `db:"thumbnail_url" json:"thumbnail_url"`
	Category     pgtype.Text `db:"category" json:"category"`
	Tags         []string    `db:"tags" json:"tags"`
	Visibility   string      `db:"visibility" json:"visibility"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
		arg.Category,
		arg.Tags,
		arg.Visibility,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		&i.Tags,
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.IsShort,
	)
	return i, err
}
