// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_history.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWatchHistory = `-- name: ListWatchHistory :many
SELECT videos.id, videos.channel_id, videos.title, videos.description, videos.status, videos.visibility, videos.views_count, videos.likes_count, videos.dislikes_count, videos.thumbnail_url, videos.original_url, videos.hls_playlist_url, videos.category, videos.tags, videos.uploaded_at, videos.published_at, videos.created_at, videos.updated_at, videos.duration, videos.is_short
FROM watch_history
JOIN videos ON videos.id = watch_history.video_id
WHERE watch_history.user_id = $1
ORDER BY watch_history.watched_at DESC
LIMIT $2 OFFSET $3
`

type ListWatchHistoryParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListWatchHistory(ctx context.Context, arg ListWatchHistoryParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listWatchHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchHistory = `-- name: UpsertWatchHistory :one
INSERT INTO watch_history (user_id, video_id, progress, completed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, video_id) DO UPDATE SET
    progress = EXCLUDED.progress,
    completed = EXCLUDED.completed,
    watched_at = NOW()
RETURNING id, user_id, video_id, watched_at, progress, completed
`

type UpsertWatchHistoryParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	VideoID   pgtype.UUID `db:"video_id" json:"video_id"`
	Progress  pgtype.Int4 `db:"progress" json:"progress"`
	Completed pgtype.Bool `db:"completed" json:"completed"`
}

func (q *Queries) UpsertWatchHistory(ctx context.Context, arg UpsertWatchHistoryParams) (WatchHistory, error) {
	row := q.db.QueryRow(ctx, upsertWatchHistory,
		arg.UserID,
		arg.VideoID,
		arg.Progress,
		arg.Completed,
	)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.WatchedAt,
		&i.Progress,
		&i.Completed,
	)
	return i, err
}
