// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_later.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addWatchLater = `-- name: AddWatchLater :exec
INSERT INTO watch_later (user_id, video_id) VALUES ($1, $2)
ON CONFLICT (user_id, video_id) DO NOTHING
`

type AddWatchLaterParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	VideoID uuid.UUID `db:"video_id" json:"video_id"`
}

func (q *Queries) AddWatchLater(ctx context.Context, arg AddWatchLaterParams) error {
	_, err := q.db.Exec(ctx, addWatchLater, arg.UserID, arg.VideoID)
	return err
}

const isInWatchLater = `-- name: IsInWatchLater :one
SELECT EXISTS (
    SELECT 1 FROM watch_later WHERE user_id = $1 AND video_id = $2
)
`

type IsInWatchLaterParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	VideoID uuid.UUID `db:"video_id" json:"video_id"`
}

func (q *Queries) IsInWatchLater(ctx context.Context, arg IsInWatchLaterParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInWatchLater, arg.UserID, arg.VideoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listWatchLater = `-- name: ListWatchLater :many
SELECT videos.id, videos.channel_id, videos.title, videos.description, videos.status, videos.visibility, videos.views_count, videos.likes_count, videos.dislikes_count, videos.thumbnail_url, videos.original_url, videos.hls_playlist_url, videos.category, videos.tags, videos.uploaded_at, videos.published_at, videos.created_at, videos.updated_at, videos.duration, videos.is_short FROM watch_later
JOIN videos ON videos.id = watch_later.video_id
WHERE watch_later.user_id = $1
ORDER BY watch_later.created_at DESC
LIMIT $2 OFFSET $3
`

type ListWatchLaterParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListWatchLater(ctx context.Context, arg ListWatchLaterParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listWatchLater, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			&i.Tags,
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.IsShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWatchLater = `-- name: RemoveWatchLater :exec
DELETE FROM watch_later WHERE user_id = $1 AND video_id = $2
`

type RemoveWatchLaterParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	VideoID uuid.UUID `db:"video_id" json:"video_id"`
}

func (q *Queries) RemoveWatchLater(ctx context.Context, arg RemoveWatchLaterParams) error {
	_, err := q.db.Exec(ctx, removeWatchLater, arg.UserID, arg.VideoID)
	return err
}
