// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error)
	IncrementVideoDislikes(ctx context.Context, id uuid.UUID) (Video, error)
	IncrementVideoLikes(ctx context.Context, id uuid.UUID) (Video, error)
	IncrementVideoViews(ctx context.Context, id uuid.UUID) (Video, error)
	ListVideosByChannel(ctx context.Context, arg ListVideosByChannelParams) ([]Video, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
