// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (channel_id, title, description , duration, status, visibility, category, tags) VALUES ($1,$2, $3, $4, $5, $6, $7, $8) RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration
`

type CreateVideoParams struct {
	ChannelID   uuid.NullUUID  `db:"channel_id" json:"channel_id"`
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	Duration    sql.NullInt32  `db:"duration" json:"duration"`
	Status      string         `db:"status" json:"status"`
	Visibility  string         `db:"visibility" json:"visibility"`
	Category    sql.NullString `db:"category" json:"category"`
	Tags        []string       `db:"tags" json:"tags"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.Duration,
		arg.Status,
		arg.Visibility,
		arg.Category,
		pq.Array(arg.Tags),
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		pq.Array(&i.Tags),
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration FROM videos WHERE id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		pq.Array(&i.Tags),
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}

const incrementVideoDislikes = `-- name: IncrementVideoDislikes :one
UPDATE videos SET dislikes_count = dislikes_count + 1 WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration
`

func (q *Queries) IncrementVideoDislikes(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, incrementVideoDislikes, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		pq.Array(&i.Tags),
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}

const incrementVideoLikes = `-- name: IncrementVideoLikes :one
UPDATE videos SET likes_count = likes_count + 1 WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration
`

func (q *Queries) IncrementVideoLikes(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, incrementVideoLikes, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		pq.Array(&i.Tags),
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}

const incrementVideoViews = `-- name: IncrementVideoViews :one
UPDATE videos SET views_count = views_count + 1 WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration
`

func (q *Queries) IncrementVideoViews(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, incrementVideoViews, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		pq.Array(&i.Tags),
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}

const listVideosByChannel = `-- name: ListVideosByChannel :many
SELECT id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration FROM videos WHERE channel_id = $1 ORDER BY uploaded_at DESC LIMIT $2 OFFSET $3
`

type ListVideosByChannelParams struct {
	ChannelID uuid.NullUUID `db:"channel_id" json:"channel_id"`
	Limit     int32         `db:"limit" json:"limit"`
	Offset    int32         `db:"offset" json:"offset"`
}

func (q *Queries) ListVideosByChannel(ctx context.Context, arg ListVideosByChannelParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.ViewsCount,
			&i.LikesCount,
			&i.DislikesCount,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.HlsPlaylistUrl,
			&i.Category,
			pq.Array(&i.Tags),
			&i.UploadedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoStatus = `-- name: UpdateVideoStatus :one
UPDATE videos SET status = $2, hls_playlist_url = $3, thumbnail_url = $4, updated_at = NOW() WHERE id = $1 RETURNING id, channel_id, title, description, status, visibility, views_count, likes_count, dislikes_count, thumbnail_url, original_url, hls_playlist_url, category, tags, uploaded_at, published_at, created_at, updated_at, duration
`

type UpdateVideoStatusParams struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Status         string         `db:"status" json:"status"`
	HlsPlaylistUrl sql.NullString `db:"hls_playlist_url" json:"hls_playlist_url"`
	ThumbnailUrl   sql.NullString `db:"thumbnail_url" json:"thumbnail_url"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideoStatus,
		arg.ID,
		arg.Status,
		arg.HlsPlaylistUrl,
		arg.ThumbnailUrl,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.ViewsCount,
		&i.LikesCount,
		&i.DislikesCount,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.HlsPlaylistUrl,
		&i.Category,
		pq.Array(&i.Tags),
		&i.UploadedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
	)
	return i, err
}
